jQuery(document).ready(function ($) {


    var FACTOR = 770;

    var KERNS = {
        '&T': -29, 
        '\'Z': -10, 
        '\'W': 9, 
        '\'V': 11, 
        '\'Q': -23, 
        '\'O': -23, 
        '\'J': -113, 
        '\'G': -23, 
        '\'C': -23, 
        '\'A': -73, 
        '(Y': 15, 
        '(V': 13, 
        '(U': -9, 
        '(T': 9, 
        '(S': -16, 
        '(Q': -28, 
        '(O': -28, 
        '(G': -28, 
        '(C': -28, 
        ')Z': -19, 
        ')Y': -39, 
        ')X': -26, 
        ')W': -16, 
        ')V': -31, 
        ')T': -26, 
        ')S': -10, 
        ')Q': -10, 
        ')O': -10, 
        ')J': -11, 
        ')G': -10, 
        ')C': -10, 
        ')A': -18, 
        '-Z': -14, 
        '-Y': -46, 
        '-X': -28, 
        '-V': -10, 
        '-T': -46, 
        '-J': -26, 
        '.Z': 17, 
        '.Y': -74, 
        '.X': 9, 
        '.W': -37, 
        '.V': -71, 
        '.U': -20, 
        '.T': -65, 
        '.S': 12, 
        '.Q': -30, 
        '.O': -30, 
        '.J': 26, 
        '.G': -27, 
        '.C': -27, 
        '.A': 23, 
        ':Y': -37, 
        ':W': -11, 
        ':V': -18, 
        ':U': -10, 
        ':T': -78, 
        ':Q': -9, 
        ':O': -9, 
        ':G': -9, 
        ':C': -9, 
        '@Z': -31, 
        '@Y': -49, 
        '@X': -36, 
        '@W': -20, 
        '@V': -33, 
        '@U': -10, 
        '@T': -40, 
        '@S': -16, 
        '@Q': -9, 
        '@O': -9, 
        '@J': -24, 
        '@G': -9, 
        '@C': -9, 
        '@A': -24, 
        'AZ': 17, 
        'AY': -73, 
        'AX': 23, 
        'AW': -16, 
        'AV': -56, 
        'AU': -9, 
        'AT': -58, 
        'AS': 14, 
        'AQ': -17, 
        'AO': -17, 
        'AJ': 27, 
        'AG': -17, 
        'AC': -17, 
        'AA': 30, 
        'BY': -23, 
        'BX': -18, 
        'BW': -11, 
        'BV': -17, 
        'CZ': 9, 
        'CY': 15, 
        'CX': 11, 
        'CV': 15, 
        'CT': 15, 
        'CS': 9, 
        'CQ': -18, 
        'CO': -18, 
        'CJ': 20, 
        'CG': -18, 
        'CC': -18, 
        'CA': 19, 
        'DZ': -13, 
        'DY': -37, 
        'DX': -22, 
        'DW': -15, 
        'DV': -15, 
        'DT': -25, 
        'DS': -9, 
        'DJ': -28, 
        'DA': -17, 
        'EU': -19, 
        'EQ': -26, 
        'EO': -26, 
        'EJ': 15, 
        'EG': -26, 
        'EC': -26, 
        'EA': 15, 
        'FY': 18, 
        'FV': 16, 
        'FT': 12, 
        'FQ': -11, 
        'FO': -11, 
        'FJ': -74, 
        'FG': -22, 
        'FC': -22, 
        'FA': -52, 
        'JZ': -15, 
        'JJ': -13, 
        'JA': -9, 
        'KZ': 18, 
        'KY': 19, 
        'KX': 24, 
        'KW': 9, 
        'KV': 18, 
        'KT': 15, 
        'KQ': -32, 
        'KO': -32, 
        'KJ': 25, 
        'KG': -32, 
        'KC': -32, 
        'KA': 31, 
        'LZ': 12, 
        'LY': -105, 
        'LX': 18, 
        'LW': -41, 
        'LV': -92, 
        'LU': -16, 
        'LT': -105, 
        'LS': 12, 
        'LQ': -41, 
        'LO': -41, 
        'LJ': 26, 
        'LG': -41, 
        'LC': -41, 
        'LA': 26, 
        'MY': -8, 
        'OZ': -13, 
        'OY': -37, 
        'OX': -27, 
        'OW': -14, 
        'OV': -20, 
        'OT': -25, 
        'OS': -9, 
        'OJ': -23, 
        'OA': -17, 
        'PX': -22, 
        'PJ': -92, 
        'PA': -46, 
        'QZ': -13, 
        'QY': -37, 
        'QX': -27, 
        'QW': -14, 
        'QV': -20, 
        'QT': -25, 
        'QS': -9, 
        'QJ': -23, 
        'QA': -17, 
        'RZ': 12, 
        'RY': -17, 
        'RX': 17, 
        'RV': -9, 
        'RQ': -9, 
        'RO': -9, 
        'RJ': 19, 
        'RG': -9, 
        'RC': -9, 
        'RA': 26, 
        'TY': 27, 
        'TX': 13, 
        'TW': 15, 
        'TV': 25, 
        'TT': 22, 
        'TQ': -25, 
        'TO': -25, 
        'TJ': -83, 
        'TG': -25, 
        'TC': -25, 
        'TA': -58, 
        'UZ': -14, 
        'UJ': -13, 
        'UA': -9, 
        'VY': 30, 
        'VX': 17, 
        'VW': 18, 
        'VV': 28, 
        'VT': 26, 
        'VQ': -20, 
        'VO': -20, 
        'VJ': -87, 
        'VG': -15, 
        'VC': -15, 
        'VA': -56, 
        'WY': 22, 
        'WX': 9, 
        'WW': 10, 
        'WV': 19, 
        'WT': 17, 
        'WQ': -14, 
        'WO': -14, 
        'WJ': -55, 
        'WG': -14, 
        'WC': -14, 
        'WA': -16, 
        'XZ': 11, 
        'XY': 17, 
        'XX': 16, 
        'XV': 15, 
        'XT': 11, 
        'XQ': -27, 
        'XO': -27, 
        'XJ': 18, 
        'XG': -22, 
        'XC': -22, 
        'XA': 25, 
        'YZ': 9, 
        'YY': 32, 
        'YX': 18, 
        'YW': 20, 
        'YV': 30, 
        'YT': 28, 
        'YQ': -37, 
        'YO': -37, 
        'YM': -8, 
        'YJ': -105, 
        'YG': -37, 
        'YC': -37, 
        'YA': -73, 
        'ZY': 10, 
        'ZV': 9, 
        'ZU': -12, 
        'ZQ': -33, 
        'ZO': -33, 
        'ZJ': 15, 
        'ZG': -33, 
        'ZC': -33, 
        'ZA': 15, 
    };


    cardRefresher.register(function(card) {
        card.find('.title .content').on('focusout', function(e) {
            var firstTwo = $(e.target).text().slice(0, 2).toUpperCase();
            var margin = (firstTwo in KERNS) ? KERNS[firstTwo] / FACTOR : 0;

            var ss = document.styleSheets;
            for (var i=0; i < ss.length; i++) {
                try {
                    var rules = ss[i].cssRules || ss[i].rules;
                    for (var j=0; j < rules.length; j++) {
                        var rule = rules[j];
                        if (rule.selectorText.includes('.card .title .content.color-first-letter:not(.editing)::first-letter')) {
                            rules[j].style['margin-right'] = margin + 'em';
                        }
                    }
                } catch (error) {}
            }
        });
    });


});
